### Intersección de trayectorias.

Tres objetos se mueven de tal manera que sus trayectorias son:
$$
2x-y+3z=24\
$$
$$
2y-z=14\
$$
$$
7x-5y=6\
$$
Encontrar su punto de intersección.

In [1]:
#Programa de eliminación Gaussiana mostrando los pasos
import numpy as np

a = np.array([[2.0, -1.0, 3.0], [0, 2.0, -1.0], [7.0, -5.0, 0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[24.0], [14.0], [6.0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
        print(f'El siguiente elemento del procedimiento es: {'\n'}{matriz_aumentada}')
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('El vector solución es :\n',gaussElimin(a,b))

La matriz de coeficientes es:
  [[ 2. -1.  3.]
 [ 0.  2. -1.]
 [ 7. -5.  0.]]
La matriz constante es:
  [[24.]
 [14.]
 [ 6.]]
La matriz aumentada es :
 [[ 2. -1.  3. 24.]
 [ 0.  2. -1. 14.]
 [ 7. -5.  0.  6.]]
El siguiente elemento del procedimiento es: 
[[  2.   -1.    3.   24. ]
 [  0.    2.   -1.   14. ]
 [  0.   -1.5 -10.5 -78. ]]
El siguiente elemento del procedimiento es: 
[[  2.    -1.     3.    24.  ]
 [  0.     2.    -1.    14.  ]
 [  0.     0.   -11.25 -67.5 ]]
El vector solución es :
 [[ 8.]
 [10.]
 [ 6.]]


### Carga de los quarks

Los protones y neutrones están formados cada uno por tres quarks. Los protones poseen dos quarks up (u) y un quark down (d), los neutrones poseen un quark up y dos quarks down. Si la carga de un protón es igual al positivo de la carga del electrón $(+e)$ y la carga de un neutrón es cero, determine las cargas de los quarks up y down. (Tip: suponga que $+e=1$.)


In [4]:
a = np.array([[2.0, 1.0], [1.0, 2.0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[1.0], [0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
        print(f'El siguiente elemento del procedimiento es: {'\n'}{matriz_aumentada}')
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('La carga de los quark up y down es:\n',gaussElimin(a,b), '\n respectivamente.' )

La matriz de coeficientes es:
  [[2. 1.]
 [1. 2.]]
La matriz constante es:
  [[1.]
 [0.]]
La matriz aumentada es :
 [[2. 1. 1.]
 [1. 2. 0.]]
El siguiente elemento del procedimiento es: 
[[ 2.   1.   1. ]
 [ 0.   1.5 -0.5]]
La carga de los quark up y down es:
 [[ 0.66666667]
 [-0.33333333]] 
 respectivamente.


### Meteoros

El Centro de Investigación 1 examina la cantidad de meteoros que entran a la atmósfera. Con su equipo de recopilación de datos durante 8 horas captó 95kg de meteoros, por fuentes externas sabemos que fueron de 4 distintas masas (1kg, 5kg, 10kg y 20kg). La cantidad total de meteoros fue de 26. Otro centro de investigación captó que la cantidad de meteoros de 5kg es 4 veces la cantidad de meteoros de 10kg, y el número de meteoros de 1kg es 1 menos que el doble de la cantidad de meteoros de 5kg. Después
use matrices para encontrar el número asociado a cada masa de meteoros.


In [7]:
a = np.array([[1.0, 5.0, 10.0, 20.0], [1.0, 1.0, 1.0, 1.0], [0, 1.0, -4.0, 0.0],[1.0, -2.0, 0, 0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[95.0], [26.0], [0], [-1.0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
        print(f'El siguiente elemento del procedimiento es: {'\n'}{matriz_aumentada}')
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('El número de meteoros de 1kg, 5kg, 10kg, 20kg es :\n',gaussElimin(a,b), '\n respectivamente')

La matriz de coeficientes es:
  [[ 1.  5. 10. 20.]
 [ 1.  1.  1.  1.]
 [ 0.  1. -4.  0.]
 [ 1. -2.  0.  0.]]
La matriz constante es:
  [[95.]
 [26.]
 [ 0.]
 [-1.]]
La matriz aumentada es :
 [[ 1.  5. 10. 20. 95.]
 [ 1.  1.  1.  1. 26.]
 [ 0.  1. -4.  0.  0.]
 [ 1. -2.  0.  0. -1.]]
El siguiente elemento del procedimiento es: 
[[  1.   5.  10.  20.  95.]
 [  0.  -4.  -9. -19. -69.]
 [  0.   1.  -4.   0.   0.]
 [  1.  -2.   0.   0.  -1.]]
El siguiente elemento del procedimiento es: 
[[  1.   5.  10.  20.  95.]
 [  0.  -4.  -9. -19. -69.]
 [  0.   1.  -4.   0.   0.]
 [  0.  -7. -10. -20. -96.]]
El siguiente elemento del procedimiento es: 
[[  1.     5.    10.    20.    95.  ]
 [  0.    -4.    -9.   -19.   -69.  ]
 [  0.     0.    -6.25  -4.75 -17.25]
 [  0.    -7.   -10.   -20.   -96.  ]]
El siguiente elemento del procedimiento es: 
[[  1.     5.    10.    20.    95.  ]
 [  0.    -4.    -9.   -19.   -69.  ]
 [  0.     0.    -6.25  -4.75 -17.25]
 [  0.     0.     5.75  13.25  24.75]]
El si